In [24]:
import pandas as pd
import numpy as np

In [25]:
data = pd.read_json('team_data.json')

In [54]:
print(data.iloc[0]['alliances'])

def get_team(df, team_name):
    team_list = []
    for i in range(df.shape[0]):
        #team_split_string = df.iloc[i]['alliances'].split('red')
        if team_name in df.iloc[i]['alliances']['blue']['team_keys']:
            team_list.append('blue')
        else:
             team_list.append('red')
    return pd.Series(team_list, name='team_alliance')

# returns dataframe of opponents and teammates
def get_opponents(df):
    teammate_1_list = []
    teammate_2_list = []
    teammate_3_list = []

    opponent_1_list = []
    opponent_2_list = []
    opponent_3_list = []

    for i in range(df.shape[0]):
        if df.iloc[i]['team_alliance'] == 'red':
            teammate_list = df.iloc[i]['alliances']['red']['team_keys']
            teammate_1_list.append(teammate_list[0])
            teammate_2_list.append(teammate_list[1])
            teammate_3_list.append(teammate_list[2])
            print(teammate_list)
            opponent_list = df.iloc[i]['alliances']['blue']['team_keys']
            opponent_1_list.append(opponent_list[0])
            opponent_2_list.append(opponent_list[1])
            opponent_3_list.append(opponent_list[2])
        else:
            teammate_list = df.iloc[i]['alliances']['blue']['team_keys']
            teammate_1_list.append(teammate_list[0])
            teammate_2_list.append(teammate_list[1])
            teammate_3_list.append(teammate_list[2])
            opponent_list = df.iloc[i]['alliances']['red']['team_keys']
            opponent_1_list.append(opponent_list[0])
            opponent_2_list.append(opponent_list[1])
            opponent_3_list.append(opponent_list[2])
    return pd.DataFrame({'Teammate1': teammate_1_list,
                         'Teammate2': teammate_2_list, 
                         'Teammate3': teammate_3_list,
                         'Opponent1': opponent_1_list,
                         'Opponent2': opponent_2_list,
                         'Opponent3': opponent_3_list
                         })




data_processed = data.join(get_team(data, 'frc422'))
data_processed = data_processed.join(get_opponents(data_processed))

{'blue': {'dq_team_keys': ['frc540'], 'score': 21, 'surrogate_team_keys': [], 'team_keys': ['frc6194', 'frc977', 'frc540']}, 'red': {'dq_team_keys': [], 'score': 23, 'surrogate_team_keys': [], 'team_keys': ['frc6802', 'frc422', 'frc2106']}}
['frc6802', 'frc422', 'frc2106']
['frc2363', 'frc422', 'frc1908']
['frc5546', 'frc422', 'frc4286']
['frc422', 'frc617', 'frc3136']
['frc422', 'frc977', 'frc3136']
['frc422', 'frc5724', 'frc401']
['frc617', 'frc2890', 'frc422']
['frc422', 'frc540', 'frc4286']
['frc5804', 'frc6194', 'frc422']

In [27]:
data_processed.head()

,actual_time,alliances,comp_level,event_key,key,match_number,post_result_time,predicted_time,score_breakdown,set_number,time,videos,winning_alliance,team_alliance,Teammate1,Teammate2,Teammate3,Opponent1,Opponent2,Opponent3
0,2022-03-05 16:26:58,"{'blue': {'dq_team_keys': ['frc540'], 'score':...",qm,2022va305,2022va305_qm10,10,2022-03-05 16:30:07,2022-03-05 16:25:55,"{'blue': {'adjustPoints': 0, 'autoCargoLowerBl...",1,1646496000,"[{'key': 'KgdSgawbe-s', 'type': 'youtube'}]",red,red,frc6802,frc422,frc2106,frc6194,frc977,frc540
1,2022-03-05 17:03:40,"{'blue': {'dq_team_keys': ['frc540'], 'score':...",qm,2022va305,2022va305_qm14,14,2022-03-05 17:07:16,2022-03-05 17:06:08,"{'blue': {'adjustPoints': 0, 'autoCargoLowerBl...",1,1646498400,"[{'key': 'ZMFgdKjC5K8', 'type': 'youtube'}]",red,red,frc2363,frc422,frc1908,frc1610,frc3136,frc540
2,2022-03-05 18:33:00,"{'blue': {'dq_team_keys': [], 'score': 18, 'su...",qm,2022va305,2022va305_qm18,18,2022-03-05 18:36:22,2022-03-05 18:34:35,"{'blue': {'adjustPoints': 0, 'autoCargoLowerBl...",1,1646502480,"[{'key': 'P9MLRP1G6Qc', 'type': 'youtube'}]",red,red,frc5546,frc422,frc4286,frc2890,frc1610,frc2106
3,2022-03-05 14:46:13,"{'blue': {'dq_team_keys': [], 'score': 34, 'su...",qm,2022va305,2022va305_qm2,2,2022-03-05 14:50:04,2022-03-05 14:47:04,"{'blue': {'adjustPoints': 0, 'autoCargoLowerBl...",1,1646491200,"[{'key': 'H8sQZe0WVlQ', 'type': 'youtube'}]",blue,red,frc422,frc617,frc3136,frc2106,frc1908,frc5804
4,2022-03-05 18:58:08,"{'blue': {'dq_team_keys': [], 'score': 23, 'su...",qm,2022va305,2022va305_qm21,21,2022-03-05 19:01:05,2022-03-05 19:00:52,"{'blue': {'adjustPoints': 0, 'autoCargoLowerBl...",1,1646504100,"[{'key': '6sKOy3Tgnsc', 'type': 'youtube'}]",red,red,frc422,frc977,frc3136,frc6194,frc4286,frc1610

In [28]:
data_processed.iloc[0]['score_breakdown']

{'blue': {'adjustPoints': 0,
  'autoCargoLowerBlue': 1,
  'autoCargoLowerFar': 0,
  'autoCargoLowerNear': 0,
  'autoCargoLowerRed': 0,
  'autoCargoPoints': 2,
  'autoCargoTotal': 1,
  'autoCargoUpperBlue': 0,
  'autoCargoUpperFar': 0,
  'autoCargoUpperNear': 0,
  'autoCargoUpperRed': 0,
  'autoPoints': 6,
  'autoTaxiPoints': 4,
  'cargoBonusRankingPoint': False,
  'endgamePoints': 6,
  'endgameRobot1': 'Mid',
  'endgameRobot2': 'None',
  'endgameRobot3': 'None',
  'foulCount': 0,
  'foulPoints': 4,
  'hangarBonusRankingPoint': False,
  'matchCargoTotal': 4,
  'quintetAchieved': False,
  'rp': 0,
  'taxiRobot1': 'Yes',
  'taxiRobot2': 'Yes',
  'taxiRobot3': 'No',
  'techFoulCount': 0,
  'teleopCargoLowerBlue': 0,
  'teleopCargoLowerFar': 0,
  'teleopCargoLowerNear': 1,
  'teleopCargoLowerRed': 0,
  'teleopCargoPoints': 5,
  'teleopCargoTotal': 3,
  'teleopCargoUpperBlue': 1,
  'teleopCargoUpperFar': 0,
  'teleopCargoUpperNear': 0,
  'teleopCargoUpperRed': 1,
  'teleopPoints': 11,
  'totalPoints': 21},
 'red': {'adjustPoints': 0,
  'autoCargoLowerBlue': 0,
  'autoCargoLowerFar': 0,
  'autoCargoLowerNear': 0,
  'autoCargoLowerRed': 0,
  'autoCargoPoints': 4,
  'autoCargoTotal': 1,
  'autoCargoUpperBlue': 0,
  'autoCargoUpperFar': 1,
  'autoCargoUpperNear': 0,
  'autoCargoUpperRed': 0,
  'autoPoints': 8,
  'autoTaxiPoints': 4,
  'cargoBonusRankingPoint': False,
  'endgamePoints': 0,
  'endgameRobot1': 'None',
  'endgameRobot2': 'None',
  'endgameRobot3': 'None',
  'foulCount': 1,
  'foulPoints': 0,
  'hangarBonusRankingPoint': False,
  'matchCargoTotal': 9,
  'quintetAchieved': False,
  'rp': 2,
  'taxiRobot1': 'Yes',
  'taxiRobot2': 'Yes',
  'taxiRobot3': 'No',
  'techFoulCount': 0,
  'teleopCargoLowerBlue': 0,
  'teleopCargoLowerFar': 0,
  'teleopCargoLowerNear': 0,
  'teleopCargoLowerRed': 1,
  'teleopCargoPoints': 15,
  'teleopCargoTotal': 8,
  'teleopCargoUpperBlue': 2,
  'teleopCargoUpperFar': 1,
  'teleopCargoUpperNear': 2,
  'teleopCargoUpperRed': 2,
  'teleopPoints': 15,
  'totalPoints': 23}}

In [31]:
def get_score_data(df, team_name):

    taxied_list = []
    endgames_list = []

    auto_lower_points_list = []
    auto_upper_points_list = []
    tele_lower_points_list = []
    tele_upper_points_list = []

    total_team_points_list = []

    # iterating through all:
    for i in range(df.shape[0]):
        team_alliance = df.iloc[i]['team_alliance']
        data_list = df.iloc[i]['score_breakdown'][team_alliance]
        # which robot were they ?
        if df.iloc[i]['Teammate1'] == team_name:
            taxied_list.append(data_list['taxiRobot1'])
            endgames_list.append(data_list['endgameRobot1'])
        if df.iloc[i]['Teammate2'] == team_name:
            taxied_list.append(data_list['taxiRobot2'])
            endgames_list.append(data_list['endgameRobot2'])
        if df.iloc[i]['Teammate3'] == team_name:
            taxied_list.append(data_list['taxiRobot3'])
            endgames_list.append(data_list['endgameRobot3'])
        
        # auto lower
        total_auto_lower_points = (data_list['autoCargoLowerBlue'] +  data_list['autoCargoLowerFar']
                                    + data_list['autoCargoLowerNear'] + data_list['autoCargoLowerRed'])
        auto_lower_points_list.append(total_auto_lower_points)

        # auto upper
        total_auto_upper_points = (data_list['autoCargoUpperBlue'] +  data_list['autoCargoUpperFar']
                                    + data_list['autoCargoUpperNear'] + data_list['autoCargoUpperRed'])
        auto_upper_points_list.append(total_auto_upper_points)

        # teleop lower
        total_teleop_lower_points = (data_list['teleopCargoLowerBlue'] +  data_list['teleopCargoLowerFar']
                                    + data_list['teleopCargoLowerNear'] + data_list['teleopCargoLowerRed'])    
        tele_lower_points_list.append(total_teleop_lower_points)

        # teleop upper
        total_teleop_upper_points = (data_list['teleopCargoUpperBlue'] +  data_list['teleopCargoUpperFar']
                                    + data_list['teleopCargoUpperNear'] + data_list['teleopCargoUpperRed'])    
        tele_upper_points_list.append(total_teleop_upper_points)

        total_team_points_list.append(data_list['totalPoints'])

    return pd.DataFrame({'Taxied': taxied_list,
                        'Hang': endgames_list,
                        'TeamAutoLower': auto_lower_points_list,
                        'TeamAutoUpper': auto_upper_points_list,
                        'TeamTeleopLower': tele_lower_points_list,
                        'TeamTeleopUpper': tele_upper_points_list,
                        'TotalTeamPoints': total_team_points_list
     })

In [32]:
data_processed = data_processed.join(get_score_data(data_processed, 'frc422'))

In [56]:
def clean_data(df, team_name):
    new_data = df.copy()
    new_data = new_data.join(get_team(df, team_name))
    new_data = new_data.join(get_opponents(new_data))
    new_data = new_data.join(get_score_data(new_data, team_name))
    new_data.drop(['actual_time', 'alliances', 'post_result_time', 'predicted_time', 'score_breakdown', 'videos', 'time'], axis=1, inplace=True)
    new_data.sort_values(by='match_number', inplace=True)
    return new_data

data_clean = clean_data(data, 'frc422')

['frc6802', 'frc422', 'frc2106']
['frc2363', 'frc422', 'frc1908']
['frc5546', 'frc422', 'frc4286']
['frc422', 'frc617', 'frc3136']
['frc422', 'frc977', 'frc3136']
['frc422', 'frc5724', 'frc401']
['frc617', 'frc2890', 'frc422']
['frc422', 'frc540', 'frc4286']
['frc5804', 'frc6194', 'frc422']

In [53]:
data_clean.head(20)

,comp_level,event_key,key,match_number,set_number,winning_alliance,team_alliance,Teammate1,Teammate2,Teammate3,Opponent1,Opponent2,Opponent3,Taxied,Hang,TeamAutoLower,TeamAutoUpper,TeamTeleopLower,TeamTeleopUpper,TotalTeamPoints
10,sf,2022va305,2022va305_sf2m1,1,2,red,blue,frc401,frc422,frc977,frc1262,frc5804,frc1610,Yes,None,0,2,1,9,43
3,qm,2022va305,2022va305_qm2,2,1,blue,red,frc422,frc617,frc3136,frc2106,frc1908,frc5804,Yes,Mid,0,1,3,2,25
11,sf,2022va305,2022va305_sf2m2,2,2,red,blue,frc401,frc422,frc977,frc1262,frc5804,frc1610,Yes,None,0,1,0,12,38
8,qm,2022va305,2022va305_qm6,6,1,red,red,frc422,frc540,frc4286,frc5546,frc1262,frc401,No,None,0,0,0,10,30
9,qm,2022va305,2022va305_qm8,8,1,red,red,frc5804,frc6194,frc422,frc401,frc6802,frc540,Yes,None,3,0,3,2,40
0,qm,2022va305,2022va305_qm10,10,1,red,red,frc6802,frc422,frc2106,frc6194,frc977,frc540,Yes,None,0,1,1,7,23
1,qm,2022va305,2022va305_qm14,14,1,red,red,frc2363,frc422,frc1908,frc1610,frc3136,frc540,Yes,None,0,3,8,19,74
2,qm,2022va305,2022va305_qm18,18,1,red,red,frc5546,frc422,frc4286,frc2890,frc1610,frc2106,Yes,None,0,1,6,0,20
4,qm,2022va305,2022va305_qm21,21,1,red,red,frc422,frc977,frc3136,frc6194,frc4286,frc1610,Yes,None,0,1,0,2,24
5,qm,2022va305,2022va305_qm24,24,1,blue,blue,frc1610,frc2363,frc422,frc6194,frc401,frc5724,Yes,None,0,4,12,20,84
6,qm,2022va305,2022va305_qm26,26,1,red,red,frc422,frc5724,frc401,frc2890,frc1610,frc1262,No,None,0,4,1,15,63
7,qm,2022va305,2022va305_qm30,30,1,blue,red,frc617,frc2890,frc422,frc5804,frc2363,frc977,Yes,None,1,1,8,4,30